redshift:
  dbname : test
  host : redshift-pruksa-datasource.c63llnrhdm9w.ap-southeast-1.redshift.amazonaws.com
  port : 5439
  user : witit_r 
  password : P@ssw0rd

sql : 
  sql_path : 'D:\winback\Programming\SQL_Script/'